### ISSUE TITLE
Validator error for AGREE Enum assignment

### ISSUE THREAD

**Issue by janetlj** [smaccm/smaccm#124] opened 2018-04-13 20:56 UTC
In OSATE 2.3.2.vfinal version, when doing an assignment from a subcomponent feature of a datatype (e.g., Status_Type in the example below) that extends Enumeration_Type, to a local variable of the same type (e.g., active_status in the example below), the validator flags it as an error for the assignment (e.g., assign active_status = sub_test.active_status; in the example below), saying that the left side of the assignment is of Status_Type, while the right side of the assignment is of Enumeration_Type.

Code example:

	data Enumeration_Type
		properties
			Data_Model::Data_Representation => Enum;
	end Enumeration_Type;	
	
	data Status_Type extends Enumeration_Type
		properties
			Data_Model::Enumerators => ("INVALID",
						"INPROGRESS", "COMPLETE");			
	end Status_Type ;

       system test
           annex agree{**
               eq active_status: Status_Type;
             };
        end test;

        system implementation test.impl
             subcomponents
                  sub_test: system sub_test;
              annex agree{**
                   assign active_status = sub_test.active_status;
              **};
          end test.impl;

          system sub_test
             features
                active_status: out data port Status_Type;
            end sub_test;

Note: changing the assign active_status = sub_test.active_status; to the following got rid of the validator error:
eq active_status2: Enumeration_Type = sub_test.active_status;

**Comment by kfhoech** [comment] 2018-04-16 11:50
Duplicated in develop branch hash e9a37102d5e00469a449e60a7ee6a3e7b5c84992.

The problem is that at AgreeJavaValidator.java:2696 the evaluation of type chases the type back to the type from which it was extended without regard to whether it is finding the component type of an AADL subcomponent or whether the type is an enumeration type.

**Comment by kfhoech** [comment] 2018-04-16 13:02
Resolved by [Pull Request](https://github.com/smaccm/smaccm/pull/125).

Thanks, @janetlj for finding this bug!

**Closed** 2018-04-16 13:03 UTC
Labels: AGREE, bug
